(define-abbrev-table 'global-abbrev-table
  '(
    ("improt" "import" nil 2)
    ("ipmort" "import" nil 2)
    ("ipmrot" "import" nil 2)
    ("reuqest" "request" nil 2)
    ("tiem" "time" nil 2)
    ("datetiem" "datetime" nil 2)
    ("itme" "item" nil 2)
    ("itmes" "items" nil 2)
    ("nto" "not" nil 2)
    ("teh" "the" nil 2)
    ("consoel" "console" nil 2)
    ("NOne" "None" nil 2)
    ("nOne" "None" nil 2)
    ("slef" "self" nil 2)
    ("fitler" "filter" nil 2)
    ("queyr" "query" nil 2)
    ("self0" "self)" nil 2)
   ))
